enum TransformType {
    RANDOMISE_POPULATION,
    GENETIC_ALGORITHM_SEARCH,
    MONTE_CARLO_SIMMULATED_ANNEALING,
    SIMPLEX_MINIMIZATION,
    ALIGN_LIGAND,
    RANDOMISE_LIGAND_BONDS,
    AGGREGATE,
    NULL_OP,
};